### ISSUE TITLE
Proposition: remove `noise` parameter

### ISSUE THREAD

**Issue by tommyod** [equinor/iterative_ensemble_smoother#104]
@dafeda Thoughts on this?

I propose removing the noise parameter altogether and writing the lines following

https://github.com/equinor/iterative_ensemble_smoother/blob/2bc4bb514058bfd6ec5c4ff13b21056227229fb8/src/iterative_ensemble_smoother/_iterative_ensemble_smoother.py#L123

as something like:

```python3
# A covariance matrix was passed
# Columns of E should be sampled from N(0,Cdd) and centered, Evensen 2019
if len(observation_errors.shape) == 2:
    E = rng.multivariate_normal(mean=np.zeros_like(num_obs), cov=observation_errors, size=ensemble_size).T
# A vector of standard deviations was passed
else:
    E = rng.normal(loc=0, scale=observation_errors, size=(ensemble_size, num_obs)).T
    
assert E.shape == (num_obs, ensemble_size)

E -= E.mean(axis=1, keepdims=True)
```

I think this is an improvement since:
- `noise` is a superfluous input parameter, since it's only used in linear combinations with `observation_errors`. Double one means halving the other, and you get the same results. So fixating one (noise) by removing it does not decrease the number of possible inputs.
- The fact that we use cholesky factorizations is an implementation detail. What we really want is to sample from a multivariate normal, and numpy has code for this. Better to delegate to numpy than to implement our own sampler.
- One parameter less to deal with when creating an instance. Randomness is better controlled by `rng` than by `rng` in combination with a random vector as input.

I might've missed something that makes removing `noise` a bad idea. Let me know!

**Comment by dafeda** [comment]
The reason why we allow `noise` as input is to let the user decide which random seed to use, but this could perhaps be solved differently.

The reason why we use cholesky factorization is that numpy's `multivariate_normal` scales poorly as the number of parameters increases.
Things might have changed, but last time I checked it was painfully slow compared to doing the Cholesky.

**Comment by tommyod** [comment]
Good reasons!

- I suggest we solve random seeds by https://github.com/equinor/iterative_ensemble_smoother/issues/102
- Didn't know it was slow. (1) we can see if the "[method](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.multivariate_normal.html#numpy.random.Generator.multivariate_normal)" argument improves speed , or (2) maybe we can add scipy as a dependency if it's faster there or (3) we just keep using cholesky but we sample the noise using `rng`

Thanks for inputs. We can call and decide what to do.
