### ISSUE TITLE
API design ideas

### ISSUE THREAD

**Issue by tommyod** [equinor/iterative_ensemble_smoother#111]
Now that I have read through the code a bit more thoroughly, here are some things I don't like about the current API:

- The `fit` and `update` methods might not need to be separate. `update` picks up where `fit` left off, and `update` does not even return anything. Is there any reason to separate them? 
- Some parameters, such as `observation_errors` (C_dd in paper) and `observation_values` (d in Paper) are sent in to `fit` in every iteration, but they never change, right? I think we should send them into the initialization instead.

To be conrete, I propose an API like this:

```python

# Every parameter that does not change in each Newton iteration (update() call) goes into the init()
model = SIES(X, C_dd, d, steplength_schedule, inversion="exact", seed=1)
# After model is initialized, E is drawn (once), and dimensions (N=realization, m=output size, n=input size)
# are inferred from X and d.

X_i = X.copy()
for iteration in range(10):
    Y_i = g(X_i)  # Evaluate the model g()
    X_i = model.update(Y_i)
    # Here X_i does not need to be explicitly passed, even if  section 2.4.3 is triggered,
    # since we can keep it internally in the model object from the previous iteration
```

Some comments:
- I want step-length to either be defined at initialization time, or at iteration time. Currently both is possible. Maybe there are some advantages, but it seems a bit redundant. You get more control if you have to input it at iteration time, because you can make a decision based on how the iterations are behaving. If you define it ahead of time you lose some control, but defining it at initialization time is more user-friendly and might be good enough.
- I want every argument that is one-time-only to go into init. Data too. Even if it's not what sklearn would've done. I think it's better that way because it separates what it updated and what is constant.
- I want to merge `fit` and `update`. I particularly don't like the name `fit`, because it has heavy connotations to sklearn and ML. So I would call the new method `update` or `iterate` or `apply_newton_step` or something.
- I want the `update` step to take in as few args as possible. Objects that can be held in state from previous iteration should be, objects that are constant go into initialization.

This breaks the typical sklearn api, where `init()` is only allowed to take in simple parameters (ints, strings, floats, etc) and not data. But the SIES is not an estimator, there's no fitting and predicting in the same ways as in an ML model. So mimicing sklearn is not as relevant as if we were implementing an ML algorithm.

Let me know yours thoughts. Maybe best to discuss over a call. I suspect there are some reasons/usecases why it's not as simple as I want it to be here. Let me know.

**Comment by dafeda** [comment]
Thanks, interesting suggestions. Let's discuss this over a call.

**Comment by tommyod** [comment]
Leave this alone for now. We should think even more generally. What kind of API would facilitate many different types of data assimilation algorithms?

- Reporting, localization, etc

**Comment by dafeda** [comment]
Can we close this now that the new API is in `main`?

**Comment by tommyod** [comment]
Yes, let's close this!
