### ISSUE TITLE
GPL vs MIT

### ISSUE THREAD

**Issue by tommyod** [equinor/iterative_ensemble_smoother#126]
The [GPL license](https://en.wikipedia.org/wiki/GNU_General_Public_License#%22Viral%22_nature) has a viral nature.

- According to [this post](https://github.com/scipy/scipy/issues/7834#issuecomment-491486393), you cannot even learn from GPL code.
- In [this post](https://github.com/scipy/scipy/issues/18118#issuecomment-1461632576), scipy appears to refuse to include GPL code.

I changed [from GPL to MIT](https://github.com/tommyod/KDEpy/issues/129) in one of my own personal projects recently, because I was not aware of this.

If we want the "viral nature" of the GPL license, then that's OK. If we do not, then we should consider a different license.

Other equinor packages have [different licenses](https://github.com/orgs/equinor/repositories?language=&q=&sort=stargazers&type=all) (no clear pattern?):

- https://github.com/equinor/design-system (MIT)
- https://github.com/equinor/segyio (GPL)
- https://github.com/equinor/xtgeo (LGPL)
- https://github.com/equinor/ert (GPL)
- https://github.com/equinor/webviz-config (MIT)
- ...

**Comment by dafeda** [comment]
What do you think @sondreso ?

**Comment by antoinecollet5** [comment]
These license stuff are very difficult to catch sometimes. For instance, what if you have a GPL and include some code from another library that's MIT. Then is the piece of code GPL or MIT ???

Personnally I have the tendancy to choose MIT for everything I do.

**Comment by markusdregi** [comment]
This library stems from [ERT](https://github.com/equinor/ert) that was strategically chosen to be GPL-licensed more than a decade ago to ensure continued open collaboration around the product. Another deliberate choice was to not introduce a CLA and hence the copyright of the product is distributed between the different contributors. In total this makes it both undesirable and unfeasible to change the license of this software package.

Regarding your comment @antoinecollet5 it is unproblematic to include an MIT-licensed dependency in a GPL-licensed project. However, the other way around would require a change of license.
