### ISSUE TITLE
Resampling perturbed observations

### ISSUE THREAD

**Issue by tommyod** [equinor/iterative_ensemble_smoother#130]
- The ESMDA paper reads (page 8, lower left) "every time we repeat the data assimilation, we resample the vector of perturbed observations, i.e., we recompute `d_uc ~ N(d_obs, alpha_i * C_D)`".
- The SIES paper has a fixed $D$ as input to Algorithm 1, where $D$ is the perturbed observations.

@dafeda and I discussed this briefly. I don't recall how it's done in ERT, but it's important to get this right.

-----------

My intuition for SIES is that resampling should not be done. Here is my explanation in Norwegian:

```text
Jeg påstår at hvis man sampler støy i hver Newton-iterasjon, så ender man opp med å underestimere
posterior-distribusjonens varians. Det er derfor ikke riktig å re-sample støyen. Argumentet mitt
er at i det aller enkleste tilfellet vil det ikke fungere, så derfor fungerer det ikke generelt
sett heller.

Anta at vi har en så bred prior at den ikke har noe å si. Anta at vi har 1 ensemble medlem og
dimensjonen på parametre og observasjoner er 1. Anta at posterior kovariansen er 1, og at
observert verdi er 0. Vi ønsker å sample fra log posterior, som blir f(x) = (x - b)^2, der b~norm().
Blir ikke enklere enn det. Vi kunne selvsagt bare samplet ~norm() direkte her og løst problemet.
Men la oss sample tilfeldige b og optimere f(x). Hvis vi gjør ett Newton steg med lengde 1,
og b er støy, så sampler vi x ~ norm(). Det er riktig. Men hvis lengden < 1 og vi
re-sampler støy, så er resultatet et snitt av ulike normalfordelte variabler fra tidligere
samples, og da går variansen ned. Tenk f.eks. 100 iterasjoner med steglengde 0.5.
Da får vi 0.5 * n_1 + 0.5^2 n_2 + ..., der n er normalfordelte variabler.
Vi får lavere varians. Enda mer ekstremt blir det når steg lengden går mot null.
```

**Comment by dafeda** [comment]
@geirev , could you please have a look at this?

**Comment by geirev** [comment]
hi, when using IES (EnRML) which is a gradient descent method, we sample the perturbed measurements once in D and use the same D in all subsequent iterations. On the other hand, ESMDA is just a sequence of independent and inflated ES updates and we need to resample D in each step to avoid bias and have a consistent result.
Hopefully this is still what ERT does!
Geir

**Comment by dafeda** [comment]
Unfortunately, ERT resamples the noise at every iteration as can be seen here:

https://github.com/equinor/ert/blob/1f63a399d23a3f61f0b1a6b4ab883311f33b9798/src/ert/analysis/_es_update.py#L536

This part of the code has been heavily refactored and I would not be surprised if a bug such as this found its way into the code.
We did not add tests of the IES (EnRML) and as far as I know, no tests failed during the refactor.

I'll create an issue in ERT.

**Comment by geirev** [comment]
good thing the bug doesn’t affect the ESMDA which is the most used, and all my adaptive localisation runs are with ESMDA as well😊

Sent from Outlook for iOS<https://aka.ms/o0ukef>

Geir Evensen
Forsker I
Research Professor

+47 51 87 56 15
+47 930 90 947

Nygårdsgaten 112, 5008 Bergen, Norway

[cid:NORCElogoe-mailsignature_8e86c798-aef0-4f72-a6e5-32122a33f894.png]

norceresearch.no<https://www.norceresearch.no/>

________________________________

**Comment by dafeda** [comment]
Yes luckily this does not effect ES-MDA.
