### ISSUE TITLE
Add a __version__ attribute

### ISSUE THREAD

**Issue by antoinecollet5** [equinor/iterative_ensemble_smoother#132]
Hi guys,

From what I have seen, the version is not hard-coded but red from GitHub (see pyproject.toml):

Following this procedure:
https://www.moritzkoerber.com/posts/versioning-with-setuptools_scm/

We could get something like:
```
import iterative_ensemble_smoother as ies
ies.__version__
````

This is quite useful when sharing a work based the library if one wants to see what version was used (in a notebook for instance).

**Comment by tommyod** [comment]
This issue was closed by PR #135
