### ISSUE TITLE
DOCS: improved documentation

### ISSUE THREAD

**Issue by antoinecollet5** [equinor/iterative_ensemble_smoother#146]
What I propose to get a better documentation:

-  Use the pydata template instead of rst: looks more modern and has a dark mode.
-  Include the readme in the doc for a nice rendering and avoid duplication
-  Make links between the bibliography and the docstrings using the :cite: directive.
-  Better API section relying on autosummary

**Comment by tommyod** [comment]
@antoinecollet5 I'm very excited about these proposed changes. Seems like a no-brainer. Please do create or (or several) PRs. Better to create several small PRs than one large PR :)

**Comment by antoinecollet5** [comment]
@tommyod Ok I wait for the other PR to be merged !

**Comment by tommyod** [comment]
This was closed by #155
