### ISSUE TITLE
Question regarding `overwrite` of `assimilate`

### ISSUE THREAD

**Issue by dafeda** [equinor/iterative_ensemble_smoother#153]
https://github.com/equinor/iterative_ensemble_smoother/blob/afc6588a4e17f02700562bf3cabf9c6991af7c5d/src/iterative_ensemble_smoother/esmda.py#L158

I would like to discuss the `assimilate` method, and in particular `overwrite` as I can't see a use case when we would like to make a copy of `X`.
In many cases users want to update large fields and surfaces, and we can't make a copy of `X`.

**Comment by tommyod** [comment]
Two comments:
- It also seems to me that ERT use-case would not involve copying `X`. On one hand, for our use case, mutating the input argument is OK. On the other hand, mutating an input argument by default is a general no-no, and clashes with what almost every API does. 
- To follow the principle of principle of least surprise, and also APIs like [scipy.linalg.solve](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve.html), I think it is nice to have an explicit argument that users can employ to say "I'm okay with you mutating the input", e.g. `overwrite=True/False`.

Related: We also make a copy to center the matrix, but issue #160 proposes a fix.

**Comment by dafeda** [comment]
Thanks for a thoughtful response.
I'm pretty sure I agree with you so closing.
