### ISSUE TITLE
Reduce memory requirements

### ISSUE THREAD

**Issue by tommyod** [equinor/iterative_ensemble_smoother#160]
Here is an idea to reduce memory requirements.
It works, but it makes the code a bit more complicated on the low-level.
The high level API stays the same.
There is a trade-off between (1) keeping it "dumb and simple" and (2) a reduction in memory usage.
If we need it, I can implement it. If we don't need it, it seems like an overcomplication.

------------------------------------------

## Reduce memory requirements

Recall that the main computation is

$X_{i+1} = X_i + \underbrace{\text{center}(X_i) \text{center}(Y)^T /(N-1)}\_{C_{MD}}   (C_{DD} + \alpha C_D)^{-1}  (D - Y)$

If we're allowed to overwrite $X$ to save memory, then we can use:

$X += \text{center}(X) \text{center}(Y)^T /(N-1)   (C_{DD} + \alpha C_D)^{-1}  (D - Y)$

Since $X$ is the largest matrix in the typical case, we can save memory if we don't explicitly form $\text{center}(X)$ as a new matrix in memory. Instead we subtract the means, compute the right hand side, add it to X, then add back the means:

```
X_parameter_mean = np.mean(X, axis=1, keepdims=True)
X -= X_parameter_mean
X += inversion(X, Y, D, alpha, ....) # compute C_MD @ inv(C_DD + alpha * C_D) @ (D - Y)
X += X_parameter_mean
```

This avoid forming a copy of $X$ to center it. 

## Rough estimation of effects on memory usage

ESMDA memory usage will be down to 47.3 MB, compared to SIES at 70 MB. This is a reduction by 1/3. Results from the `test_memory_usage` test, with 
```
ensemble_size = 100
num_params = 1000
num_obs = 10000
```
Even bigger effect can be expected if `num_params` is larger.

**Comment by tommyod** [comment]
@dafeda - yay or nay?

**Comment by dafeda** [comment]
> @dafeda - yay or nay?

Good idea!
I suggest we consider this more carefully after the adaptive localization milestone.

**Comment by tommyod** [comment]
I am an idiot. Let $C_{MD} = (X (I - \mathbf{1}\mathbf{1}^T)/N) (Y (I - \mathbf{1}\mathbf{1}^T)/N)^T / (N-1)$. Denote $P = (I - \mathbf{1}\mathbf{1}^T)/N$. We have $C_{MD} = X P P^T Y^T / (N-1)$, but $P^T = P$, and $P$ is idempotent (a projection) since $P^2 = P$.

This means that we can choose to either center $X$ or center $Y$. We don't have to center both to compute the empirical covariance matrix. In our application $X$ is larger than $Y$, so we can center $Y$ and save memory and computation time.

**Comment by tommyod** [comment]
For the reason above, this was not needed. We simply avoid centering $X$. This was done in #162
