### ISSUE TITLE
Small mistake in docstring of `empirical_cross_covariance`

### ISSUE THREAD

**Issue by dafeda** [equinor/iterative_ensemble_smoother#170]
https://github.com/equinor/iterative_ensemble_smoother/blob/1817bfa051b28e72c80bbb803a419a46f6b3c246/src/iterative_ensemble_smoother/esmda_inversion.py#L39

`Y` has shape (number of observations, ensemble_size).

**Comment by dafeda** [comment]
No longer an issue.

**Comment by tommyod** [comment]
Fixed :)
