### ISSUE TITLE
Integrate back into ert

### ISSUE THREAD

**Issue by eivindjahren** [equinor/iterative_ensemble_smoother#2]
https://github.com/equinor/ert should use the iterative_ensemble_smoother package to do its calculations. Likely some of the code in the repository as of [7036c2f](https://github.com/equinor/iterative_ensemble_smoother/commit/7036c2fb25cc8796eee96e3052a0c994356cbe42) will remain in ert and be removed from iterative_ensemble_smoother.

Some of the candidates for being removed from iterative_ensemble_smoother is

* [ies_data.cpp](https://github.com/equinor/iterative_ensemble_smoother/blob/1112b5cc158f1bd3e86b3e881d57e2a33cd9dc52/src/iterative_ensemble_smoother/ies_data.cpp) and [ies_data.hpp](https://github.com/equinor/iterative_ensemble_smoother/blob/1112b5cc158f1bd3e86b3e881d57e2a33cd9dc52/src/iterative_ensemble_smoother/ies_data.hpp)
* [ies_config.cpp](https://github.com/equinor/iterative_ensemble_smoother/blob/1112b5cc158f1bd3e86b3e881d57e2a33cd9dc52/src/iterative_ensemble_smoother/ies_config.cpp) and [ies_config.hpp](https://github.com/equinor/iterative_ensemble_smoother/blob/1112b5cc158f1bd3e86b3e881d57e2a33cd9dc52/src/iterative_ensemble_smoother/ies_config.hpp) except we need to keep `ies::inversion_type`.
* `ies::linalg_store_active_W` in [ies.cpp](https://github.com/equinor/iterative_ensemble_smoother/blob/1112b5cc158f1bd3e86b3e881d57e2a33cd9dc52/src/iterative_ensemble_smoother/ies.cpp) 
* `ies::init_update` in [ies.cpp](https://github.com/equinor/iterative_ensemble_smoother/blob/1112b5cc158f1bd3e86b3e881d57e2a33cd9dc52/src/iterative_ensemble_smoother/ies.cpp) 
* `ies::updateA` in [ies.cpp](https://github.com/equinor/iterative_ensemble_smoother/blob/1112b5cc158f1bd3e86b3e881d57e2a33cd9dc52/src/iterative_ensemble_smoother/ies.cpp)

**Comment by dafeda** [comment]
ERT now uses the `iterative_ensemble_smoother` package for smoothing.
After major cleanup all mentioned files and functions are gone except `updateA` which is in use.
