### ISSUE TITLE
ensemble_smoother_update_step should be just IterativeEnsembleSmoother.update_step(step_length=1, iteration_nr=1)

### ISSUE THREAD

**Issue by eivindjahren** [equinor/iterative_ensemble_smoother#27]
`ensemble_smoother_update_step` is just a simplified version of `IterativeEnsembleSmoother.update_step` where `step_length` is always `1.0` and `iteration_nr` is always `1`. Therefore, `ensemble_smoother_update_step` should not exist, and it should be possible to perform this simplified update step by setting parameters in `IterativeEnsembleSmoother`. However, before this is done, it should be verified that these produce the same result.

**Comment by dafeda** [comment]
Consider #65 as well
