### ISSUE TITLE
What does `build_ext` do in `setup.py`?

### ISSUE THREAD

**Issue by dafeda** [equinor/iterative_ensemble_smoother#37]
[According to the docs](https://pybind11.readthedocs.io/en/stable/compiling.html#building-with-setuptools):

>If you want to do an automatic search for the highest supported C++ standard, that is supported via a build_ext command override; it will only affect Pybind11Extensions:

Is this needed as we explicitly set `cxx_std=17` in `Pybind11Extension`?

https://github.com/equinor/iterative_ensemble_smoother/blob/3ba6f29f0564bdec58a1546b679d16128d93461c/setup.py#L23

**Comment by eivindjahren** [comment]
> Is this needed as we explicitly set `cxx_std=17` in `Pybind11Extension`?

Its used to get Pybind to build at all.

**Comment by dafeda** [comment]
Thanks, seems to me we can do without since we are explicitly setting cxx_std=17.
