### ISSUE TITLE
Test that one iteration of SIES with step-length 1 (ES implementation) equals original ES algorithm from Evensen 2009

### ISSUE THREAD

**Issue by Blunde1** [equinor/iterative_ensemble_smoother#76]
Create a test `test_that_sies1_and_es_implementation_equals_original_es():`
One iteration of SIES 1 with step length one (currently implementation definition of ES) should equal the original ES from Evensen 2009. It is given as 
<img width="481" alt="image" src="https://user-images.githubusercontent.com/13650516/222144449-6361423b-9451-4b7d-a23b-5ad2106bdba0.png">
Note that notation here is different from Evensen 2019 and the implementation of SIES.

**Comment by tommyod** [comment]
I will close this. We test that 1 step works on the linear case as expected.
