### ISSUE TITLE
`makeE` great again

### ISSUE THREAD

**Issue by dafeda** [equinor/iterative_ensemble_smoother#85]
According to `evensen2019`, $E$ is the centered measurement-perturbation matrix whose columns are sampled from $N(0, C_{dd})$ and divided by $\sqrt{N-1}$.

The current implementation does an additional scaling of each row of $E$ as a function of observation errors.
It is not clear why this is done, but the effect seems to be that the rows of the noise matrix with larger observation errors are scaled more than those with smaller observation errors.
Without this scaling, we might potentially be "unlucky" in the draw of $E$ and up with small ensemble perturbations.

Nevertheless, without having good theoretical reasons for doing any of this extra work, we should just sample from $N(0, C_{dd})$ and use that as the noise matrix.

Here's the current implementation for reference: 

```c++
MatrixXd makeE(const VectorXd &obs_errors, const MatrixXd &noise) {
  int active_obs_size = obs_errors.rows();
  int active_ens_size = noise.cols();


  MatrixXd E = noise;
  VectorXd pert_mean = E.rowwise().mean();
  E = E.colwise() - pert_mean;
  VectorXd pert_var = E.cwiseProduct(E).rowwise().sum();


  for (int i = 0; i < active_obs_size; i++) {
    double factor = obs_errors(i) * sqrt(active_ens_size / pert_var(i));
    E.row(i) *= factor;
  }


  return E;
}
```

**Comment by Blunde1** [comment]
Note that elements of `noise` are independnetly sampled standard uniform $N(0,1)$ and `obs_errors` is the root-diagonal of $C_{dd}$, i.e. the standard deviations.
